# Generated by Django 2.1.3 on 2018-12-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
    ]
