# Generated by Django 2.1.3 on 2018-12-07 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
