# Generated by Django 2.1.3 on 2018-12-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='likes',
        ),
    ]
