# Generated by Django 2.1.3 on 2018-12-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
